//
// Created by jo.colomban on 2023-11-28.
//

#ifndef FUTUREGAMES_ALGOSANDDATASTRUCTURESASSIGNEMENT_STOPWATCH_H
#define FUTUREGAMES_ALGOSANDDATASTRUCTURESASSIGNEMENT_STOPWATCH_H



class Stopwatch {

};



#endif //FUTUREGAMES_ALGOSANDDATASTRUCTURESASSIGNEMENT_STOPWATCH_H
